version: '3'

services:
  data_harvester:
    build:
      context: ../../
      dockerfile: ./scripts/docker_dev/Dockerfile
    volumes:
      - ../../:/usr/src/app:consistent
      - ./TESTS/:/TESTS:consistent
    links:
      - redis
    command: bash -c "source activate service && python -c \"from yodapy.utils.creds import set_credentials_file;set_credentials_file(data_source='ooi', username='$${USERNAME}', token='$${TOKEN}')\" && pushd scripts && huey_consumer.py main.huey --workers 100 --worker-type greenlet"
  redis:
    image: redis
    ports:
      - 6379:6379
    hostname: redis
    expose:
      - 6379